name: cron-ping
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    concurrency:
      group: cron-ping
      cancel-in-progress: true
    steps:
      - run: echo "Ping at $(date -u)"
