name: early-event-scan
on:
  schedule:
    - cron: "*/2 * * * *"   # every 10 minutes
  workflow_dispatch: {}       # run manually
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Restore state
        id: state
        uses: actions/cache@v4
        with:
          path: state.json
          key: state-${{ github.run_id }}
          restore-keys: |
            state-
      - name: Run scanner
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scanner.py
      - name: Save state & logs back to repo (fallback)
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state.json alerts.csv outcomes.csv || true
          git commit -m "Update state/logs" || true
          git push || true

