name: early-event-scan

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch: {}

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: ${{ github.repository }}-repo-writes
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Quick syntax check
        run: python -m py_compile scanner.py

      - name: Write heartbeat (proof it ran)
        run: echo "last_run_utc=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > heartbeat.txt

      - name: Run scanner
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scanner.py

      - name: Commit state & logs (safe rebase + retry)
        if: always()
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage changes first
          git add -A || true

          # Nothing to commit? Exit cleanly.
          if git diff --cached --quiet; then
            echo "Nothing to commit"
            exit 0
          fi

          # Rebase with autostash to avoid conflicts
          git pull --rebase --autostash || true

          # Commit and push (retry a few times if another workflow pushed)
          git commit -m "scan: update state/logs [skip ci]" || true
          for i in 1 2 3; do
            if git push; then
              echo "Pushed successfully"
              exit 0
            else
              git pull --rebase --autostash || true
              sleep 2
            fi
          done

          echo "Push failed after retries"
          exit 1

