name: Market Hype Scan

on:
  workflow_dispatch: {}
  schedule:
    # every 10 minutes, Mon–Fri (UTC). Your script already gates by market hours.
    - cron: "*/10 * * * 1-5"

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        env:
          # 🔔 set this Secret in GitHub: Settings → Secrets and variables → Actions → New repository secret
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

          # --- Watchlist news thresholds (lowered so it fires more) ---
          SINGLE_POST_MIN_SCORE: "20"
          SINGLE_POST_MIN_COMMENTS: "10"
          REQUIRED_MATCHES: "2"
          CLUSTER_WINDOW_MIN: "60"
          COOLDOWN_MIN_NEWS: "9"

          # --- Cross-platform hype scan (Reddit + non-Reddit RSS) ---
          HYPE_SCAN_ENABLED: "1"
          HYPE_MIN_HITS: "2"
          HYPE_MIN_Z: "1.5"
          HYPE_SEND_DISCORD: "1"

          # Add more non-Reddit RSS feeds here (comma-separated)
          EXTRA_RSS: "https://fortune.com/feed/,https://www.technologyreview.com/feed/,https://feeds.a.dj.com/rss/RSSMarketsMain.xml"

          # Price spikes on watchlist (silent CSV logging)
          PRICE_SPIKES_ENABLED: "1"
        run: |
          python scanner.py

      - name: Commit results (alerts/outcomes/signals/state)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: scanner run [skip ci]"
          file_pattern: |
            alerts.csv
            outcomes.csv
            signals.csv
            spikes.csv
            labels.csv
            state.json
