name: early-event-scan

on:
  schedule:
    - cron: "*/10 * * * *"     # every 10 minutes (UTC)
  workflow_dispatch: {}         # manual "Run workflow" button

jobs:
  scan:
    runs-on: ubuntu-latest

    # needed to push state/logs back to the repo
    permissions:
      contents: write

    # serialize any repo writes across workflows to avoid collisions
    concurrency:
      group: ${{ github.repository }}-repo-writes
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # full history so rebase works

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Quick syntax check
        run: python -m py_compile scanner.py

      - name: Write heartbeat (proof it ran)
        run: echo "last_run_utc=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" > heartbeat.txt

      - name: Run scanner
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scanner.py

      - name: Commit state & logs (safe rebase + retry)
        if: always()
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add state.json alerts.csv outcomes.csv heartbeat.txt || true
          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "scan: update state/logs [skip ci]"
            for i in 1 2 3; do
              if git push; then
                break
              else
                git pull --rebase && sleep 2
              fi
            done
          fi

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json alerts.csv outcomes.csv heartbeat.txt || true
          git commit -m "scan: update state/logs [skip ci]" || true
          git push || true
