name: train-model

on:
  schedule:
    - cron: "30 21 * * MON-FRI"   # 5:30pm ET on weekdays
    - cron: "45 14 * * MON-FRI"   # 10:45am ET: grabs yesterday’s late +60m, early today outcomes
  workflow_dispatch: {}

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.repository }}-repo-writes
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python train.py

      - name: Commit model & metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add model/model.pkl model/metrics.json || true
          git commit -m "model: update" || true
          git push || true
