name: weekly-summary

on:
  schedule:
    - cron: "0 14 * * MON"   # Mondays 14:00 UTC (~10:00 AM ET)
  workflow_dispatch: {}

jobs:
  summary:
    runs-on: ubuntu-latest

    # read is enough (we don't push in this job)
    permissions:
      contents: read

    # share the same repo-write lock so we never collide with the scan job
    concurrency:
      group: ${{ github.repository }}-repo-writes
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Quick syntax check
        run: python -m py_compile scanner.py

      - name: Restore state & logs (if not committed yet)
        uses: actions/cache@v4
        with:
          path: |
            state.json
            alerts.csv
            outcomes.csv
          key: weekly-${{ github.run_id }}
          restore-keys: |
            weekly-
            scan-
            state-

      - name: Post weekly summary
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MODE: weekly
          SUMMARY_LOOKBACK_DAYS: "7"
        run: python scanner.py
